ALTER TYPE "ConversationStep" ADD VALUE 'MEAL_EDIT';
ALTER TYPE "ConversationStep" ADD VALUE 'MEAL_DELETE';
ALTER TYPE "ConversationStep" ADD VALUE 'WORKOUT_EDIT';
ALTER TYPE "ConversationStep" ADD VALUE 'WORKOUT_EDIT_EXERCISE';
ALTER TYPE "ConversationStep" ADD VALUE 'WORKOUT_DELETE';
